[tool.poetry]
name = "py-concepts"
version = "0.1.0"
description = ""
authors = ["Ivan Vekhov <ivekhov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ipython = "^8.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
